name: Test and Validate

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        php-version: [7.4, 8.0, 8.1, 8.2]
        
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup PHP ${{ matrix.php-version }}
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}
        extensions: zip, curl, mbstring, json
        tools: composer:v2
        
    - name: Validate composer.json
      run: composer validate --strict
      
    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ matrix.php-version }}-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-${{ matrix.php-version }}-
          
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress
      
    - name: Check PHP syntax
      run: find . -name "*.php" -not -path "./vendor/*" -exec php -l {} \;
      
    - name: Run basic tests
      run: |
        # Test plugin file structure
        test -f wp-authenticator.php
        test -d includes/
        test -d routes/
        test -f includes/class-jwt-handler.php
        test -f routes/rest-routes.php
        echo "✅ Plugin structure validated"
        
  build-test:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: zip, curl, mbstring, json
        tools: composer:v2
        
    - name: Test build process
      run: |
        # Install production dependencies
        composer install --no-dev --optimize-autoloader --no-interaction
        
        # Test plugin can be built
        mkdir -p test-build/wp-authenticator
        cp -r includes/ test-build/wp-authenticator/includes/
        cp -r routes/ test-build/wp-authenticator/routes/
        cp -r vendor/ test-build/wp-authenticator/vendor/
        cp wp-authenticator.php test-build/wp-authenticator/
        
        # Verify required files exist
        test -f test-build/wp-authenticator/wp-authenticator.php
        test -f test-build/wp-authenticator/vendor/autoload.php
        test -d test-build/wp-authenticator/vendor/firebase/
        echo "✅ Build test passed"
